---
title: "PSTAT 131 HW 2"
author: "Luke Todd"
date: "4/10/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(here)
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggthemes)
library(yardstick)
tidymodels_prefer()

abalone <- read_csv(here("data/abalone.csv"))

```

### Question 1

```{r}

abalone <- abalone %>% 
  mutate(age = rings + 1.5)

hist(abalone$age)

```

The age of abalones appears to have a normal distribution.


### Question 2

```{r} 

set.seed(3068)

abalone_split <- initial_split(abalone, prop = 0.80,
                               strata = age)

abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)

```

### Question 3

```{r}

abalone_recipe <- recipe(age ~ type + 
                           longest_shell + 
                           diameter + 
                           height + 
                           whole_weight + 
                           shucked_weight + 
                           viscera_weight + 
                           shell_weight, 
                         data = abalone_train) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_interact(terms = ~ type:shucked_weight +
                  longest_shell:diameter +
                  shucked_weight:shell_weight) %>%
  step_center() %>%
  step_scale()

```

We should use rings to predict age because we are trying to figure out a better way to predict age that is not through the rings. Rings are logistically hard to measure.

### Questions 4, 5, 6

```{r}

# Question 4

lm_model <- linear_reg() %>%
  set_engine("lm")

# Question 5

lm_wflow <- workflow() %>%
  add_model(lm_model) %>%
  add_recipe(abalone_recipe)

lm_fit <- fit(lm_wflow, abalone_train)

tib <- lm_fit %>%
  extract_fit_parsnip() %>%
  tidy()

# Question 6

new_data <- data.frame(type = "F", longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1)

predict(lm_fit, new_data = new_data)


```

The hypothetical female abalone age would be around 13.6 years old.

### Question 7

```{r}

metrics <- metric_set(rmse, rsq, mae)

abalone_train_res <- predict(lm_fit, new_data = abalone_train)

abalone_train_res %>% head()

abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))

abalone_train_res %>% head()

metrics(abalone_train_res, truth = age, estimate = .pred)

```









